### ISSUE TITLE
Unable to get client list: 500 [object Object]

### ISSUE THREAD

**Issue by marinjurjevic** [CoRfr/docker-leshan#1]
I run container with following line:

```
docker run --restart always -d -p 8081:8081 -p 5683:5683/udp -p 5684:5684/udp --name leshan-server corfr/leshan server -wp 8081
```

Logs from docker container:

<details>
<summary>docker logs leshan-server</summary>
<p>

```
2021-05-26 10:48:12,756 INFO LeshanServer - LWM2M server started at coap:///0.0.0.0:5683 coaps:///0.0.0.0:5684
2021-05-26 10:48:12,920 INFO LeshanServerDemo - Web server started at http://0.0.0.0:8081/.
+ java -jar ./leshan-server-demo.jar -wp 8081
2021-05-26 11:06:46,857 INFO LeshanServer - LWM2M server started at coap:///0.0.0.0:5683 coaps:///0.0.0.0:5684
2021-05-26 11:06:46,963 INFO LeshanServerDemo - Web server started at http://0.0.0.0:8081/.
2021-05-26 14:42:07,623 ERROR SendableResponse - Exception while calling the reponse sent callback
java.lang.reflect.InaccessibleObjectException: Unable to make private java.util.Collections$EmptyMap() accessible: module java.base does not "opens java.util" to unnamed module @7aa8031d
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:188)
	at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:181)
	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.makeAccessible(UnsafeReflectionAccessor.java:44)
	at com.google.gson.internal.ConstructorConstructor.newDefaultConstructor(ConstructorConstructor.java:103)
	at com.google.gson.internal.ConstructorConstructor.get(ConstructorConstructor.java:85)
	at com.google.gson.internal.bind.MapTypeAdapterFactory.create(MapTypeAdapterFactory.java:127)
	at com.google.gson.Gson.getAdapter(Gson.java:458)
	at com.google.gson.Gson.toJson(Gson.java:696)
	at com.google.gson.Gson.toJsonTree(Gson.java:597)
	at com.google.gson.Gson.toJsonTree(Gson.java:576)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.serialize(TreeTypeAdapter.java:155)
	at org.eclipse.leshan.server.demo.servlet.json.RegistrationSerializer.serialize(RegistrationSerializer.java:53)
	at org.eclipse.leshan.server.demo.servlet.json.RegistrationSerializer.serialize(RegistrationSerializer.java:29)
	at com.google.gson.internal.bind.TreeTypeAdapter.write(TreeTypeAdapter.java:81)
	at com.google.gson.Gson.toJson(Gson.java:704)
	at com.google.gson.Gson.toJson(Gson.java:683)
	at com.google.gson.Gson.toJson(Gson.java:638)
	at com.google.gson.Gson.toJson(Gson.java:618)
	at org.eclipse.leshan.server.demo.servlet.EventServlet$1.registered(EventServlet.java:84)
	at org.eclipse.leshan.server.registration.RegistrationServiceImpl.fireRegistered(RegistrationServiceImpl.java:74)
	at org.eclipse.leshan.server.registration.RegistrationHandler$1.run(RegistrationHandler.java:84)
	at org.eclipse.leshan.core.response.SendableResponse.sent(SendableResponse.java:47)
	at org.eclipse.leshan.server.californium.registration.RegisterResource.handleRegister(RegisterResource.java:183)
	at org.eclipse.leshan.server.californium.registration.RegisterResource.handlePOST(RegisterResource.java:98)
	at org.eclipse.californium.core.CoapResource.handleRequest(CoapResource.java:227)
	at org.eclipse.leshan.core.californium.LwM2mCoapResource.handleRequest(LwM2mCoapResource.java:51)
	at org.eclipse.californium.core.server.ServerMessageDeliverer.deliverRequest(ServerMessageDeliverer.java:106)
	at org.eclipse.californium.core.network.stack.BaseCoapStack$StackTopAdapter.receiveRequest(BaseCoapStack.java:204)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
	at org.eclipse.californium.core.network.stack.BlockwiseLayer.receiveRequest(BlockwiseLayer.java:413)
	at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:275)
	at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:84)
	at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:137)
	at org.eclipse.californium.core.network.CoapEndpoint$1.receiveRequest(CoapEndpoint.java:309)
	at org.eclipse.californium.core.network.UdpMatcher$2.run(UdpMatcher.java:270)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:289)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-05-26 14:42:16,787 WARN HttpChannel - /api/clients

```

</p>
</details>

**Comment by cdh4u** [comment]
I didn't check your logs in details, but it seems I had a similar problem.

I did not manage to solve it, so what I did was taking an ubuntu image, and then installed both openjdk and leshan during the docker build. That worked.

**Comment by marinjurjevic** [comment]
I encountered this again without running in docker environment. Happened with latest leshan 1.3.2-SNAPSHOT jar.

EDIT: This happens when running with JDK 16, with JDK 11 it works normally!
